name: app_spark
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # íconos iOS/Android
  cupertino_icons: ^1.0.8

  # HTTP para peticiones
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Aquí registramos el asset de tu imagen Spark.png
  assets:
    - assets/images/Spark.png